from .go_to_planet import SpaceshipGoToPlanetDiscreteEnv, SpaceshipGoToPlanetContinuousEnv
from .do_not_crash import DoNotCrashDiscreteEnv, DoNotCrashContinuousEnv
from .orbit import SpaceshipOrbitDiscreteEnv, SpaceshipOrbitContinuousEnv
from .land import SpaceshipLandDiscreteEnv, SpaceshipLandContinuousEnv
from .hover_1d import Hover1DDiscreteEnv, Hover1DContinuousEnv