from .go_to_planet import SpaceshipGoToPlanetDiscreteEnv, SpaceshipGoToPlanetContinuousEnv
from .do_not_crash import SpaceshipDoNotCrashDiscreteEnv, SpaceshipDoNotCrashContinuousEnv
from .orbit import SpaceshipOrbitDiscreteEnv, SpaceshipOrbitContinuousEnv
from .land import SpaceshipLandDiscreteEnv, SpaceshipLandContinuousEnv
from .hover_1d import SpaceshipHover1DDiscreteEnv, SpaceshipHover1DContinuousEnv